### ISSUE TITLE
浏览器内双击链接，直接后台打开新标签页

### ISSUE THREAD

**Issue by GregAMO** [mthli/Ninja2#5]
我日常中“后台打开新标签页”这个动作特别频繁，
无论是从其他软件还是在浏览器内。
目前在用的浏览器很喜欢的功能就是：
长按链接直接在后台打开新标签页
（无论显示为网址、文字、图片）
不过这个功能是带着一个快捷开关
关掉就是普通的长按后弹出选项菜单。

这样日常中切换还是有一些麻烦的。
然而那款软件开发不太搭理Android这边了，很多其他方面渐渐跟不上。

所以，Ninja有没可能：
浏览器内双击链接
（无论显示为网址、文字、图片）
就后台打开新标签页内？

感谢开发这款浏览器
让我刷酷安和telegram都很爽了233

**Comment by mthli** [comment]
还是长按对话框吧。
