### ISSUE TITLE
在页面加载时 URL 区域会显示拼写错误的红线，而且会闪烁

### ISSUE THREAD

**Issue by hjkcai** [mthli/Ninja2#7]
抱歉这个问题难以提供截图/重现演示…**似乎是加载进度条每刷新一次就闪一下**

机器环境是 Android 7.1.1 r6, Nexus 5X, Pure Nexus (https://forum.xda-developers.com/nexus-5x/development/rom-pure-nexus-layers-fi-wifi-calling-t3244601)

**Comment by mthli** [comment]
升级到最新版 v2.5.1 试试。
